[0m14:53:59.315005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76bcb5533d70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76bcb40ca240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76bcb40caf60>]}


============================== 14:53:59.321022 | 13982a37-effd-4a0b-ba05-af658b4ee375 ==============================
[0m14:53:59.321022 [info ] [MainThread]: Running with dbt=1.10.1
[0m14:53:59.321521 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/jelte/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt seed', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:53:59.321916 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/jelte/projects/lineage_tracker/generate_data/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:53:59.323255 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.061059907, "process_in_blocks": "77320", "process_kernel_time": 0.323346, "process_mem_max_rss": "96580", "process_out_blocks": "8", "process_user_time": 1.159314}
[0m14:53:59.323699 [debug] [MainThread]: Command `dbt seed` failed at 14:53:59.323608 after 0.06 seconds
[0m14:53:59.324005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76bcb4031970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76bcb5533d70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76bcb42dd8e0>]}
[0m14:53:59.324328 [debug] [MainThread]: Flushing usage events
[0m14:53:59.812758 [debug] [MainThread]: An error was encountered while trying to flush usage events
